name: CI
on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v4
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "pnpm"

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "release"

      - name: Install Rserve
        run: |
          install.packages("Rserve", repos="http://rforge.net", type="source")
        shell: Rscript {0}

      - run: pnpm install --no-frozen-lockfile

      - name: Start Rserve
        run: pnpm run rserve &

      - run: pnpm run ci
