name: CI
on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "release"

      - name: Install Rserve
        run: |
          install.packages("Rserve", repos="http://rforge.net", type="source")
        shell: Rscript {0}

      - run: bun install

      - name: Start Rserve
        run: bun run rserve &

      - run: bun run ci
